--task 1
SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID

--task-2

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID


--task 3

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID

--task 4

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D ON E.DEPT_ID=D.DEPT_ID

--Task 5

SELECT EMP_NAME, DEPT_NAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

--task 6

SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) AS FULL_NAME
FROM CUSTOMERS;


--task 7

SELECT INITCAP(FIRST_NAME), INITCAP(LAST_NAME) FROM CUSTOMERS;

task 8

SELECT UPPER(FIRST_NAME), LOWER(EMAIL) FROM CUSTOMERS;

task 9

SELECT LOWER(EMAIL), LENGTH(EMAIL) FROM CUSTOMERS;

--task 10 

SELECT PHONE, LPAD(PHONE, 15, '*'), RPAD(PHONE, 15, '-') FROM CUSTOMERS;

--task 11

SELECT EMAIL, SUBSTRING(EMAIL FOR 4) AS first_4_chars, SUBSTRING(EMAIL FROM POSITION('@' IN EMAIL) + 1) AS domain_name
FROM CUSTOMERS;

